Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    #master server with load balancing
    config.vm.define "jdecorteS" do |master|
        master.vm.box = "generic/debian12"
        master.vm.hostname = "jdecorteS"
        master.vm.network :private_network, ip: "192.168.56.110"
        master.vm.provision :shell, path: "scripts/master.sh"
        master.vm.provision :shell, inline: <<-SHELL
            kubectl apply -f /vagrant/confs/ingress.yaml
            kubectl apply -f /vagrant/confs/app1.yaml
            kubectl apply -f /vagrant/confs/app2.yaml
            kubectl apply -f /vagrant/confs/app3.yaml
        SHELL
    end

    config.vm.provider :virtualbox do |v|
        v.memory = 2024
        v.cpus = 2
    end
end
