Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    #master server
    config.vm.define "mgomes-dS" do |master|
        master.vm.box = "generic/debian12"
        master.vm.hostname = "mgomes-dS"
        master.vm.network :private_network, ip: "192.168.56.110"
        master.vm.provision :shell, path: "scripts/master.sh"
    end

    #node server
    config.vm.define "mgomes-dSW" do |worker|
        worker.vm.box = "generic/debian12"
        worker.vm.hostname = "mgomes-dSW"
        worker.vm.network :private_network, ip: "192.168.56.111"
        worker.vm.provision :shell, path: "scripts/worker.sh"
    end

    config.vm.provider :virtualbox do |v|
        v.memory = 1024
        v.cpus = 1
    end
end
